version: '3.8'

services:
  backend:
    build: ./expense_tracker_backend
    ports:
      - "5000:5000"
    env_file:
      - ./expense_tracker_backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./expense-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
